INSERT INTO temas (nombre, nivel, contenido, enlace) VALUES ('Pentagrama', 0, 'El pentagrama o pauta musical es un conjunto de cinco líneas horizontales paralelas y equidistantes sobre el cual se escriben las notas musicales y otros signos de notación.', 'https://es.wikipedia.org/wiki/Pentagrama');
INSERT INTO temas (nombre, nivel, contenido, enlace) VALUES ('Escalas', 1, 'La escala musical es un grupo de notas musicales ordenadas, donde dichas notas se ordenarán según su altura, de esta forma, a medida que cada nota de la escala asciende éstas son más agudas, y a medida que descienden, se vuelven más graves.', 'https://www.skoove.com/blog/es/escalas-musicales/');
INSERT INTO temas (nombre, nivel, contenido, enlace) VALUES ('Acordes', 2, 'Un acorde consiste en un conjunto de dos o más notas diferentes (tocadas al mismo tiempo) y que constituyen una unidad armónica.​ En determinados contextos, un acorde también puede ser percibido como tal aunque no suenen todas sus notas.​ Pueden formarse acordes con las notas de un mismo instrumento o con notas de diferentes instrumentos (incluyendo la voz humana) tocados a la vez, incluso con notas de distintas octavas.', 'https://es.wikipedia.org/wiki/Acorde');

INSERT INTO temas (nombre, nivel, contenido, enlace) VALUES ('Notas', 0, 'Las notas musicales se nombran de la siguiente manera: Do, Re, Mi, Fa, Sol, La y Si, (en cifrado: C, D, E, F, G, A, B). Además de las notas con alteraciones como sostenidos y bemoles. Se dibujan sobre el pentagrama con símbolos o dibujos que representan qué nota es, su duración y su altura dependiendo del lugar en el pentagrama en donde se coloquen y de la clave musical en la que se encuentren. Las notas musicales se combinan entre sí para formar melodías o para formar armonías.', 'https://creatumusica.art/2022/06/25/notas-musicales/');
INSERT INTO temas (nombre, nivel, contenido, enlace) VALUES ('Alteraciones', 1, 'Las alteraciones son unos signos que pueden aparecer al lado izquierdo de las notas musicales o después de la clave (armadura). Estos signos modifican la altura de la nota. Es decir, con la alteración, la nota ya no sonará como siempre, sino un poco más aguda o más grave.', 'https://www.musicaypunto.es/las-alteraciones/');
INSERT INTO temas (nombre, nivel, contenido, enlace) VALUES ('Armonía', 2, 'La armonía musical es el proceso mediante el cual los sonidos individuales son unidos para formar un acorde o una estructura de acordes en una pieza musical. El estudio de la armonía incluye también la armonía vertical (acordes) y la armonía horizontal (melodía). La armonía, junto con la melodía y el ritmo es parte de uno de los tres elementos básicos de la música.', 'https://creatumusica.art/2022/09/21/armonia-musical/');



INSERT INTO ejemplos (tema_id, nota, tipo_escala, descripcion, enlace) VALUES (2, 'Do', 'Mayor', 'Do, Re, Mi, Fa, Sol, La, Si, Do', 'https://creatumusica.art/2022/07/02/escala-de-do/');
INSERT INTO ejemplos (tema_id, nota, tipo_escala, descripcion, enlace) VALUES (2, 'Fa', 'Mayor','Fa, Sol, La, Sib, Do, Re, Mi, Fa',  'https://creatumusica.art/2023/01/25/escala-de-fa/');
INSERT INTO ejemplos (tema_id, nota, tipo_escala, descripcion, enlace) VALUES (3, 'Do', 'Menor', 'Do, Mib, Sol', 'https://creatumusica.art/2022/04/30/acorde-de-do-menor/');

INSERT INTO ejemplos (tema_id, nota, tipo_escala, descripcion, enlace) VALUES (4, 'Do', null, 'Do, Do#, Dob', 'https://es.wikipedia.org/wiki/Do_(nota)');
INSERT INTO ejemplos (tema_id, nota, tipo_escala, descripcion, enlace) VALUES (4, 'La', null, 'La, La#, Lab', 'https://es.wikipedia.org/wiki/La_(nota)');
INSERT INTO ejemplos (tema_id, nota, tipo_escala, descripcion, enlace) VALUES (5, 'Fa', null, 'Fa#',  'https://www.youtube.com/watch?v=xma47UZP9dU');

INSERT INTO ejercicios (tema_id, nota, tipo_escala, enunciado, enlace) VALUES (2, 'Do', 'Mayor', '¿Qué tipo de escala corresponde la siguiente secuencia de notas? \nDo, Re, Mi, Fa, Sol, La, Si, Do', 'https://creatumusica.art/2022/07/02/escala-de-do/');
INSERT INTO ejercicios (tema_id, nota, tipo_escala, enunciado, enlace) VALUES (2, 'Sol', 'Mayor','¿Qué tipo de escala corresponde la siguiente secuencia de notas? \nSol, La, Si, Do, Re, Mi, Fa#, Sol',  'https://creatumusica.art/2023/02/03/escala-de-sol/');
INSERT INTO ejercicios (tema_id, nota, tipo_escala, enunciado, enlace) VALUES (2, 'La', 'Menor', '¿Qué tipo de escala corresponde la siguiente secuencia de notas? \nLa, Si, Do, Re, Mi, Fa Sol, La', 'https://creatumusica.art/2023/02/11/escala-de-la/');